### ISSUE TITLE
Adding image markers at runtime does not work

### ISSUE THREAD

**Issue by AbRezaei** [onirix-ar/webar-sdk-samples#2]
I am using this code to develop an experience where I can add markers at runtime.
According to the document on your site, this can be done using the following snippet:
```
     const imageURL = 'https://upload.wikimedia.org/wikipedia/commons/f/fc/EAM_Nuvolari_S1_640x480.jpg';
     OX.addImage(imageURL);
```
But I get this error every time:
```
TypeError: Cannot read properties of undefined (reading 'HEAPU8')
     at g.addImage (ox-sdk.esm.js:1:5096283)
     at ox-sdk.esm.js:1:5119806
```

**Comment by somepablo** [comment]
Hi,

The `addImage` function has recently changed its signature and internal behaviour and those changes were not yet reflected in our documentation. We have just updated the doc to provide a working example for the current published version (1.1.2).

Please, follow these steps:

1. Use SDK version 1.1.2
2. Initialise the SDK on ImageTracking mode (`init` function).
3. Start tracking (`start` function).
4. Add any images you want to track by calling `addImage` function. Here it is an updated snippet:

```
 const imageId = 'custom image id';
 const imageURL = 'https://upload.wikimedia.org/wikipedia/commons/f/fc/EAM_Nuvolari_S1_640x480.jpg';

 OX.addImage(imageURL, imageId);
```

Hope it helps
